@echo off
setlocal EnableExtensions EnableDelayedExpansion

:: =============================================================================
:: SQL Tools - Build Script (Feature Subset Aware)
:: =============================================================================
:: Usage examples:
::   build.bat
::   build.bat --features DB_AUTOMATION
::   build.bat --features DB_AUTOMATION,INSERT_CONSOLIDATOR
::   build.bat --features ALL
:: =============================================================================

set "ALL_FEATURES_CSV=INSERT_CONSOLIDATOR,DB_AUTOMATION,WORKFILE_GENERATOR,MULTI_SCHEMA"
set "FEATURES_ARG="
set "UNKNOWN_ARG="

:: Change to the script directory first so relative paths always work
cd /d "%~dp0"

:parse_args
if "%~1"=="" goto args_done
set "ARG=%~1"

if /I "%ARG%"=="--help" goto show_help
if /I "%ARG%"=="-h" goto show_help

if /I "%ARG%"=="--features" (
    if "%~2"=="" (
        call :fail "Missing value for --features. Example: --features DB_AUTOMATION,WORKFILE_GENERATOR"
        goto finish
    )
    set "FEATURES_ARG=%~2"
    shift
    shift
    goto parse_args
)

if /I "%ARG:~0,11%"=="--features=" (
    set "FEATURES_ARG=%ARG:~11%"
    shift
    goto parse_args
)

:: Compatibility fallback: first non-flag arg treated as features list
if "%ARG:~0,1%"=="-" (
    set "UNKNOWN_ARG=%ARG%"
    call :fail "Unknown argument: %UNKNOWN_ARG%. Use --help for valid options."
    goto finish
)

if not defined FEATURES_ARG (
    set "FEATURES_ARG=%ARG%"
    shift
    goto parse_args
)

set "UNKNOWN_ARG=%ARG%"
call :fail "Unknown extra argument: %UNKNOWN_ARG%. Use --help for valid options."
goto finish

:args_done
if not defined FEATURES_ARG set "FEATURES_ARG=ALL"

call :resolve_selected_features "%FEATURES_ARG%"
if errorlevel 1 goto finish

set "FEATURE_TAG=%SELECTED_FEATURES:,=+%"
if /I "%SELECTED_FEATURES%"=="%ALL_FEATURES_CSV%" set "FEATURE_TAG=FULL"

echo.
echo  ================================================
echo   SQL Tools - Building EXE...
echo  ================================================
echo   Parsed features : %SELECTED_FEATURES%
echo   Build tag       : %FEATURE_TAG%
echo.

:: Get current date in YYYYMMDD format using PowerShell
for /f "usebackq" %%I in (`powershell -NoProfile -Command "Get-Date -Format 'yyyyMMdd'"`) do set YYYYMMDD=%%I
set "OUT_NAME=%YYYYMMDD% SQL Tools [%FEATURE_TAG%].exe"

:: Generate build profile metadata for runtime
if not exist "generated" mkdir "generated"
> "generated\build_profile.py" echo # Auto-generated by build.bat. Do not edit manually.
>> "generated\build_profile.py" echo ENABLED_FEATURES = [
for %%F in (%SELECTED_FEATURES:,= %) do (
    >> "generated\build_profile.py" echo     "%%F",
)
>> "generated\build_profile.py" echo ]

set "SQL_TOOLS_FEATURES=%SELECTED_FEATURES%"

:: Clean previous build artifacts for a fresh build (ONLY the build cache, keep dist)
echo  [1/3] Cleaning build cache...
if exist "build" rmdir /s /q "build"

:: Run PyInstaller with the spec file
echo  [2/3] Running PyInstaller...
python -m PyInstaller "SQL Tools.spec" --noconfirm
if errorlevel 1 (
    call :fail "PyInstaller failed. See error lines above."
    goto finish
)

:: Check if build succeeded and rename output
echo.
if exist "dist\SQL Tools.exe" (
    echo  [3/3] Renaming output with profile tag...
    move /Y "dist\SQL Tools.exe" "dist\%OUT_NAME%" >nul

    echo  ================================================
    echo   SUCCESS! EXE is ready at:
    echo   %~dp0dist\%OUT_NAME%
    echo  ================================================
    echo.
    echo  File size:
    for %%A in ("dist\%OUT_NAME%") do echo    %%~zA bytes
) else (
    call :fail "Build finished but dist\\SQL Tools.exe was not found."
)

goto finish

:resolve_selected_features
set "RAW=%~1"
set "RAW=%RAW:\"=%"
set "RAW=%RAW: =%"

if not defined RAW (
    call :fail "Empty --features value."
    exit /b 1
)

if /I "%RAW%"=="ALL" (
    set "SELECTED_FEATURES=%ALL_FEATURES_CSV%"
    exit /b 0
)

set "SELECTED_FEATURES="
set "INVALID_FEATURES="

for %%F in (%RAW:,= %) do (
    if /I "%%F"=="INSERT_CONSOLIDATOR" (
        call :append_feature INSERT_CONSOLIDATOR
    ) else if /I "%%F"=="DB_AUTOMATION" (
        call :append_feature DB_AUTOMATION
    ) else if /I "%%F"=="WORKFILE_GENERATOR" (
        call :append_feature WORKFILE_GENERATOR
    ) else if /I "%%F"=="MULTI_SCHEMA" (
        call :append_feature MULTI_SCHEMA
    ) else (
        if defined INVALID_FEATURES (
            set "INVALID_FEATURES=!INVALID_FEATURES!,%%F"
        ) else (
            set "INVALID_FEATURES=%%F"
        )
    )
)

if defined INVALID_FEATURES (
    call :fail "Invalid feature token(s): %INVALID_FEATURES%"
    echo         Valid values: %ALL_FEATURES_CSV%
    exit /b 1
)

if not defined SELECTED_FEATURES (
    call :fail "No valid features were selected."
    echo         Valid values: %ALL_FEATURES_CSV%
    exit /b 1
)

exit /b 0

:append_feature
set "FEATURE_TO_ADD=%~1"
if not defined SELECTED_FEATURES (
    set "SELECTED_FEATURES=%FEATURE_TO_ADD%"
    goto :eof
)

set "HAYSTACK=,%SELECTED_FEATURES%,"
if /I "!HAYSTACK:,%FEATURE_TO_ADD%,=!" NEQ "!HAYSTACK!" goto :eof
set "SELECTED_FEATURES=%SELECTED_FEATURES%,%FEATURE_TO_ADD%"
goto :eof

:show_help
echo.
echo SQL Tools build options:
echo   --features LIST
echo.
echo LIST can be:
echo   ALL
echo.
echo Or a comma-separated subset of:
echo   INSERT_CONSOLIDATOR,DB_AUTOMATION,WORKFILE_GENERATOR,MULTI_SCHEMA
echo.
echo Examples:
echo   build.bat --features DB_AUTOMATION
echo   build.bat --features DB_AUTOMATION,WORKFILE_GENERATOR
echo   build.bat DB_AUTOMATION,WORKFILE_GENERATOR
goto finish

:fail
echo.
echo [ERROR] %~1
set "BUILD_FAILED=1"
goto :eof

:finish
echo.
if defined BUILD_FAILED (
    echo Build ended with errors.
) else (
    echo Build script completed.
)
echo.
pause
if defined BUILD_FAILED exit /b 1
exit /b 0
