"""
Multi-Schema SQL Combiner Logic Module
=======================================
Takes one or more SQL workfiles (generated by Workfile Generator) and produces
a single combined .sql file with each script repeated for every selected schema,
with the USE statement replaced appropriately.

Author: Abhinav Prasad
"""

import re
import os
from datetime import datetime
from pathlib import Path


# Default known schemas (pre-selected in the UI)
DEFAULT_SCHEMAS = [
    "db_ostrum_ltn",
    "db_ostrum_lgw",
    "db_ostrum_beg",
    "db_ostrum_scl",
    "db_ostrum_dmo",
    "db_ostrum_jfk",
]

# Regex to match the USE statement line (with or without trailing comment)
# Matches patterns like:
#   USE db_ostrum_ltn;
#   USE db_ostrum_ltn; -- db_ostrum_ltn; db_ostrum_lgw; ...
_USE_PATTERN = re.compile(
    r'^\s*USE\s+\S+;.*$',
    re.IGNORECASE | re.MULTILINE
)


def replace_use_statement(sql_content: str, target_schema: str) -> str:
    """
    Replace the USE statement line in a SQL workfile with a new schema.

    Handles:
    - USE db_ostrum_ltn;
    - USE db_ostrum_ltn; -- db_ostrum_ltn; db_ostrum_lgw; db_ostrum_beg; ...

    Returns the modified SQL content.
    """
    replacement = f"USE {target_schema};"
    result, count = _USE_PATTERN.subn(replacement, sql_content, count=1)
    if count == 0:
        # No USE statement found — prepend one so the script still runs correctly
        result = f"USE {target_schema};\n\n{sql_content}"
    return result


def get_file_object_name(sql_content: str, filename: str) -> str:
    """
    Try to extract an object name from the SQL content for labelling purposes.
    Falls back to the filename stem if not found.
    """
    match = re.search(
        r'CREATE\s+(?:OR\s+REPLACE\s+)?(?:PROCEDURE|FUNCTION|TRIGGER|VIEW)\s+`?(\w+)`?',
        sql_content,
        re.IGNORECASE
    )
    if match:
        return match.group(1)
    return Path(filename).stem


def _build_combined_sql(source_items: list[tuple[str, str]], selected_schemas: list) -> str:
    """Build combined SQL content from source items and target schemas."""
    formatted_date = datetime.now().strftime("%d %b %Y")
    schema_list_str = ", ".join(selected_schemas)

    header_block = (
        f"-- =================================================================\n"
        f"-- MULTI-SCHEMA DEPLOYMENT\n"
        f"-- Generated : {formatted_date}\n"
        f"-- Schemas   : {schema_list_str}\n"
        f"-- Files     : {len(source_items)}\n"
        f"-- =================================================================\n"
    )

    sections = [header_block]

    for schema_idx, schema in enumerate(selected_schemas, start=1):
        sections.append(
            f"\n\n"
            f"-- -----------------------------------------------------------------\n"
            f"-- SCHEMA: {schema}  ({schema_idx}/{len(selected_schemas)})\n"
            f"-- -----------------------------------------------------------------\n"
        )

        for source_name, content in source_items:
            obj_name = get_file_object_name(content, source_name)
            modified = replace_use_statement(content, schema)
            sections.append(
                f"\n-- [{source_name}]  →  {obj_name}\n"
                f"{modified.strip()}\n"
            )

    return "\n".join(sections)


def _load_file_sources(file_paths: list) -> tuple[list[tuple[str, str]], list[str]]:
    """Read SQL file contents and return (sources, errors)."""
    source_items = []
    errors = []

    for fp in file_paths:
        try:
            with open(fp, 'r', encoding='utf-8') as f:
                content = f.read()
            source_items.append((os.path.basename(fp), content))
        except Exception as e:
            errors.append(f"{os.path.basename(fp)}: {str(e)}")

    return source_items, errors


def combine_for_schemas(
    file_paths: list,
    selected_schemas: list,
    output_path: str,
    date_prefix: str | None = None,
) -> dict:
    """
    Reads each file in file_paths and produces a single combined SQL file
    that contains every script repeated for every schema in selected_schemas,
    grouped by schema.

    Args:
        file_paths:       List of absolute paths to .sql workfiles.
        selected_schemas: List of schema names (e.g. ['db_ostrum_ltn', 'db_ostrum_lgw']).
        output_path:      Full path (including filename) for the output file.
        date_prefix:      Optional YYYYMMDD string for the header; defaults to today.

    Returns:
        dict with keys:
            'output_file'     : str  — absolute path of the generated file
            'schemas'         : list — schemas used
            'files_processed' : int  — number of source files combined
            'errors'          : list — any per-file error messages
    """
    results = {
        'output_file': None,
        'schemas': selected_schemas,
        'files_processed': 0,
        'errors': [],
    }

    if not selected_schemas:
        results['errors'].append("No schemas selected.")
        return results

    if not file_paths:
        results['errors'].append("No files provided.")
        return results

    source_items, errors = _load_file_sources(file_paths)
    results['errors'].extend(errors)

    if not source_items:
        results['errors'].append("No files could be read.")
        return results

    combined_sql = _build_combined_sql(source_items, selected_schemas)

    # --- Write output ---
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w', encoding='utf-8', newline='\n') as f:
        f.write(combined_sql)

    results['output_file'] = str(output_path)
    results['files_processed'] = len(source_items)
    return results


def combine_for_schemas_to_clipboard(
    file_paths: list,
    selected_schemas: list,
    date_prefix: str | None = None,
) -> dict:
    """
    Reads each file in file_paths and builds the combined multi-schema SQL
    string without writing anything to disk.

    Args:
        file_paths:       List of absolute paths to .sql workfiles.
        selected_schemas: List of schema names.
        date_prefix:      Optional YYYYMMDD string for the header; defaults to today.

    Returns:
        dict with keys:
            'content'         : str  — the full combined SQL string to copy
            'schemas'         : list — schemas used
            'files_processed' : int  — number of source files combined
            'errors'          : list — any per-file error messages
    """
    results = {
        'content': '',
        'schemas': selected_schemas,
        'files_processed': 0,
        'errors': [],
    }

    if not selected_schemas:
        results['errors'].append("No schemas selected.")
        return results

    if not file_paths:
        results['errors'].append("No files provided.")
        return results

    source_items, errors = _load_file_sources(file_paths)
    results['errors'].extend(errors)

    if not source_items:
        results['errors'].append("No files could be read.")
        return results

    combined_sql = _build_combined_sql(source_items, selected_schemas)

    results['content'] = combined_sql
    results['files_processed'] = len(source_items)
    return results


def combine_text_for_schemas(
    raw_sql: str,
    selected_schemas: list,
    output_path: str,
    source_name: str = "Pasted SQL",
) -> dict:
    """
    Build a multi-schema output file using one pasted SQL source block.

    Returns:
        dict with keys:
            'output_file'     : str  — absolute path of the generated file
            'schemas'         : list — schemas used
            'files_processed' : int  — number of source blocks combined (always 1)
            'errors'          : list — validation or processing errors
    """
    results = {
        'output_file': None,
        'schemas': selected_schemas,
        'files_processed': 0,
        'errors': [],
    }

    if not selected_schemas:
        results['errors'].append("No schemas selected.")
        return results

    content = raw_sql.strip()
    if not content:
        results['errors'].append("No SQL text provided.")
        return results

    source_items = [(source_name, content)]
    combined_sql = _build_combined_sql(source_items, selected_schemas)

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w', encoding='utf-8', newline='\n') as f:
        f.write(combined_sql)

    results['output_file'] = str(output_path)
    results['files_processed'] = 1
    return results


def combine_text_for_schemas_to_clipboard(
    raw_sql: str,
    selected_schemas: list,
    source_name: str = "Pasted SQL",
) -> dict:
    """
    Build multi-schema SQL in-memory using one pasted SQL source block.

    Returns:
        dict with keys:
            'content'         : str  — the full combined SQL string to copy
            'schemas'         : list — schemas used
            'files_processed' : int  — number of source blocks combined (always 1)
            'errors'          : list — validation or processing errors
    """
    results = {
        'content': '',
        'schemas': selected_schemas,
        'files_processed': 0,
        'errors': [],
    }

    if not selected_schemas:
        results['errors'].append("No schemas selected.")
        return results

    content = raw_sql.strip()
    if not content:
        results['errors'].append("No SQL text provided.")
        return results

    source_items = [(source_name, content)]
    results['content'] = _build_combined_sql(source_items, selected_schemas)
    results['files_processed'] = 1
    return results


def get_sql_files_from_folder(folder_path: str) -> list:
    """Return sorted list of .sql file paths in a folder."""
    return sorted(str(p) for p in Path(folder_path).glob("*.sql"))
